var info_kwarc_sally_comm_text = {
  name: 'info_kwarc_sally_comm_text',
  defaultElementNamespaceURI: 'http:\/\/kwarc.info\/sally\/comm\/text',
  typeInfos: [{
      type: 'classInfo',
      localName: 'GetText',
      propertyInfos: []
    }, {
      type: 'classInfo',
      localName: 'AutocompleteResponse',
      propertyInfos: [{
          type: 'element',
          name: 'suggestion',
          collection: true,
          elementName: 'suggestion',
          typeInfo: 'info_kwarc_sally_comm_text.AutocompleteResponse.Suggestion'
        }]
    }, {
      type: 'classInfo',
      localName: 'AutocompleteResponse.Suggestion',
      propertyInfos: [{
          type: 'element',
          name: 'concept',
          elementName: 'concept',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'text',
          elementName: 'text',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'AutocompleteRequest',
      propertyInfos: [{
          type: 'element',
          name: 'path',
          elementName: 'path',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'text',
          elementName: 'text',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'prefix',
          elementName: 'prefix',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'col',
          elementName: 'col',
          typeInfo: 'Int'
        }, {
          type: 'element',
          name: 'line',
          elementName: 'line',
          typeInfo: 'Int'
        }]
    }, {
      type: 'classInfo',
      localName: 'GetTextResponse',
      propertyInfos: [{
          type: 'element',
          name: 'text',
          elementName: 'text',
          typeInfo: 'String'
        }]
    }],
  elementInfos: [{
      elementName: 'GetText',
      typeInfo: 'info_kwarc_sally_comm_text.GetText'
    }, {
      elementName: 'AutocompleteResponse',
      typeInfo: 'info_kwarc_sally_comm_text.AutocompleteResponse'
    }, {
      elementName: 'AutocompleteRequest',
      typeInfo: 'info_kwarc_sally_comm_text.AutocompleteRequest'
    }, {
      elementName: 'GetTextResponse',
      typeInfo: 'info_kwarc_sally_comm_text.GetTextResponse'
    }]
};

define("info_kwarc_sally_comm_text", function(){});

// Generated by CoffeeScript 1.7.1
define('text',['require','sally_client','info_kwarc_sally_comm_text'],function(require) {
  var Text, context, marshaller, unmarshaller;
  require("sally_client");
  require("info_kwarc_sally_comm_text");
  context = new Jsonix.Context([info_kwarc_sally_comm_text]);
  marshaller = context.createMarshaller();
  unmarshaller = context.createUnmarshaller();
  return Text = (function() {
    function Text(repoURL, docPath, repoInstanceID) {
      this.repoURL = repoURL;
      this.docPath = docPath;
      this.repoInstanceID = repoInstanceID != null ? repoInstanceID : null;
    }

    Text.prototype.getName = function() {
      return "text";
    };

    Text.prototype.marshal = function(obj) {
      return marshaller.marshalString(obj);
    };

    Text.prototype.unmarshal = function(str) {
      return unmarshaller.unmarshalString(str);
    };

    Text.prototype.handleMessage = function(msg, sendBack) {};

    return Text;

  })();
});

