// Generated by CoffeeScript 1.4.0

define(function(require) {
  var ScriptableToolbar;
  return ScriptableToolbar = (function() {

    function ScriptableToolbar(id, interpretter) {
      this.id = id;
      this.interpretter = interpretter;
    }

    ScriptableToolbar.prototype.addButton = function(btnId, name, script) {
      var me;
      me = this;
      $(this.id).append("<button id='" + btnId + "'>" + name + "</button>");
      return $("#" + btnId).click(function() {
        return me.interpretter.exec(script);
      });
    };

    ScriptableToolbar.prototype.init = function(data) {
      var id, item, _results;
      _results = [];
      for (id in data) {
        item = data[id];
        _results.push(this.addButton(id, item.name, item.code));
      }
      return _results;
    };

    return ScriptableToolbar;

  })();
});
