// Generated by CoffeeScript 1.4.0

define(function(require) {
  var Interpreter;
  return Interpreter = (function() {

    function Interpreter(env) {
      this.env = env;
    }

    Interpreter.prototype.exec = function(script) {
      var s;
      try {
        eval("with (this.env) { s = eval(script); }");
      } catch (e) {
        s = e;
      }
      if ((s != null) && (s.toString != null)) {
        return s.toString();
      }
    };

    Interpreter.prototype.autocomplete = function(string, callback) {
      var prop, results;
      results = [];
      for (prop in this.env) {
        console.log("prop", prop);
        if (prop.indexOf(string) === 0) {
          results.push(prop);
        }
      }
      return callback(results);
    };

    return Interpreter;

  })();
});
