// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var TexUtils, TextUtils;
  TextUtils = require("text_utils");
  TexUtils = (function(_super) {

    __extends(TexUtils, _super);

    function TexUtils(editor) {
      this.editor = editor;
      TexUtils.__super__.constructor.call(this, editor);
    }

    TexUtils.prototype.getEnvironmentAtPos = function(pos) {
      var cnt, result;
      if (!(pos != null)) {
        pos = this.editor.getCursorPosition();
      }
      cnt = {};
      result = null;
      this.searchReverse(pos, /\\(begin|end)\{([a-zA-Z0-9- ]+)\}/g, function(pos, match) {
        if (!(cnt[match[2]] != null)) {
          cnt[match[2]] = 0;
        }
        if (match[1] === "end") {
          cnt[match[2]]--;
        } else {
          cnt[match[2]]++;
        }
        if (cnt[match[2]] > 0) {
          result = match[2];
          return false;
        }
      });
      return result;
    };

    return TexUtils;

  })(TextUtils);
  return TexUtils;
});
